# DO NOT EDIT THIS FILE!
#
# Python module IEV_INJ__POA generated by omniidl

import omniORB
omniORB.updateModule("IEV_INJ__POA")

# ** 1. Stub files contributing to this module
import IEV_INJ_idl

# ** 2. Sub-modules

# ** 3. End
