# DO NOT EDIT THIS FILE!
#
# Python module ITMSET generated by omniidl

import omniORB
omniORB.updateModule("ITMSET")

# ** 1. Stub files contributing to this module
import ITMSET_idl

# ** 2. Sub-modules

# ** 3. End
