# Python stubs generated by omniidl from ICLOCK_PRO.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


# #include "ICLOCK.idl"
import ICLOCK_idl
_0_ICLOCK = omniORB.openModule("ICLOCK")
_0_ICLOCK__POA = omniORB.openModule("ICLOCK__POA")

# #include "IBASE.idl"
import IBASE_idl
_0_IBASE = omniORB.openModule("IBASE")
_0_IBASE__POA = omniORB.openModule("IBASE__POA")

# #include "IBASE_IF.idl"
import IBASE_IF_idl
_0_IBASE_IF = omniORB.openModule("IBASE_IF")
_0_IBASE_IF__POA = omniORB.openModule("IBASE_IF__POA")

#
# Start of module "ICLOCK_PRO"
#
__name__ = "ICLOCK_PRO"
_0_ICLOCK_PRO = omniORB.openModule("ICLOCK_PRO", r"ICLOCK_PRO.idl")
_0_ICLOCK_PRO__POA = omniORB.openModule("ICLOCK_PRO__POA", r"ICLOCK_PRO.idl")


# interface TimeMngr
_0_ICLOCK_PRO._d_TimeMngr = (omniORB.tcInternal.tv_objref, "IDL:ICLOCK_PRO/TimeMngr:1.0", "TimeMngr")
omniORB.typeMapping["IDL:ICLOCK_PRO/TimeMngr:1.0"] = _0_ICLOCK_PRO._d_TimeMngr
_0_ICLOCK_PRO.TimeMngr = omniORB.newEmptyClass()
class TimeMngr :
    _NP_RepositoryId = _0_ICLOCK_PRO._d_TimeMngr[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ICLOCK_PRO.TimeMngr = TimeMngr
_0_ICLOCK_PRO._tc_TimeMngr = omniORB.tcInternal.createTypeCode(_0_ICLOCK_PRO._d_TimeMngr)
omniORB.registerType(TimeMngr._NP_RepositoryId, _0_ICLOCK_PRO._d_TimeMngr, _0_ICLOCK_PRO._tc_TimeMngr)

# TimeMngr operations and attributes
TimeMngr._d_setMode = ((omniORB.typeMapping["IDL:ICLOCK/TimeMode:1.0"], ), (omniORB.typeMapping["IDL:ICLOCK/TimeState:1.0"], ), None)
TimeMngr._d_getMode = ((), (omniORB.typeMapping["IDL:ICLOCK/TimeMode:1.0"], ), None)
TimeMngr._d_setDataStreams = ((omniORB.typeMapping["IDL:IBASE/Longs:1.0"], ), (omniORB.typeMapping["IDL:ICLOCK/TimeState:1.0"], ), None)
TimeMngr._d_getDataStreams = ((), (omniORB.typeMapping["IDL:IBASE/Longs:1.0"], ), None)
TimeMngr._d_setSampleTime = ((omniORB.typeMapping["IDL:IBASE/Time:1.0"], ), (omniORB.typeMapping["IDL:ICLOCK/TimeState:1.0"], ), None)
TimeMngr._d_getSampleTime = ((), (omniORB.typeMapping["IDL:IBASE/Time:1.0"], ), None)
TimeMngr._d_setIntervalMode = ((omniORB.typeMapping["IDL:IBASE/Time:1.0"], ), (omniORB.typeMapping["IDL:ICLOCK/TimeState:1.0"], ), None)
TimeMngr._d_setPacketMode = ((), (omniORB.typeMapping["IDL:ICLOCK/TimeState:1.0"], ), None)
TimeMngr._d_isPacketMode = ((), (omniORB.tcInternal.tv_boolean, ), None)
TimeMngr._d_step = ((), (omniORB.typeMapping["IDL:ICLOCK/TimeState:1.0"], ), None)
TimeMngr._d_getMinTime = ((), (omniORB.typeMapping["IDL:IBASE/Time:1.0"], ), None)
TimeMngr._d_getMaxTime = ((), (omniORB.typeMapping["IDL:IBASE/Time:1.0"], ), None)
TimeMngr._d_getUTC = ((), (omniORB.typeMapping["IDL:IBASE/Time:1.0"], ), None)
TimeMngr._d_getDeltaTimeToUTC = ((), (omniORB.typeMapping["IDL:IBASE/Time:1.0"], ), None)

# TimeMngr object reference
class _objref_TimeMngr (CORBA.Object):
    _NP_RepositoryId = TimeMngr._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def setMode(self, *args):
        return self._obj.invoke("setMode", _0_ICLOCK_PRO.TimeMngr._d_setMode, args)

    def getMode(self, *args):
        return self._obj.invoke("getMode", _0_ICLOCK_PRO.TimeMngr._d_getMode, args)

    def setDataStreams(self, *args):
        return self._obj.invoke("setDataStreams", _0_ICLOCK_PRO.TimeMngr._d_setDataStreams, args)

    def getDataStreams(self, *args):
        return self._obj.invoke("getDataStreams", _0_ICLOCK_PRO.TimeMngr._d_getDataStreams, args)

    def setSampleTime(self, *args):
        return self._obj.invoke("setSampleTime", _0_ICLOCK_PRO.TimeMngr._d_setSampleTime, args)

    def getSampleTime(self, *args):
        return self._obj.invoke("getSampleTime", _0_ICLOCK_PRO.TimeMngr._d_getSampleTime, args)

    def setIntervalMode(self, *args):
        return self._obj.invoke("setIntervalMode", _0_ICLOCK_PRO.TimeMngr._d_setIntervalMode, args)

    def setPacketMode(self, *args):
        return self._obj.invoke("setPacketMode", _0_ICLOCK_PRO.TimeMngr._d_setPacketMode, args)

    def isPacketMode(self, *args):
        return self._obj.invoke("isPacketMode", _0_ICLOCK_PRO.TimeMngr._d_isPacketMode, args)

    def step(self, *args):
        return self._obj.invoke("step", _0_ICLOCK_PRO.TimeMngr._d_step, args)

    def getMinTime(self, *args):
        return self._obj.invoke("getMinTime", _0_ICLOCK_PRO.TimeMngr._d_getMinTime, args)

    def getMaxTime(self, *args):
        return self._obj.invoke("getMaxTime", _0_ICLOCK_PRO.TimeMngr._d_getMaxTime, args)

    def getUTC(self, *args):
        return self._obj.invoke("getUTC", _0_ICLOCK_PRO.TimeMngr._d_getUTC, args)

    def getDeltaTimeToUTC(self, *args):
        return self._obj.invoke("getDeltaTimeToUTC", _0_ICLOCK_PRO.TimeMngr._d_getDeltaTimeToUTC, args)

omniORB.registerObjref(TimeMngr._NP_RepositoryId, _objref_TimeMngr)
_0_ICLOCK_PRO._objref_TimeMngr = _objref_TimeMngr
del TimeMngr, _objref_TimeMngr

# TimeMngr skeleton
__name__ = "ICLOCK_PRO__POA"
class TimeMngr (PortableServer.Servant):
    _NP_RepositoryId = _0_ICLOCK_PRO.TimeMngr._NP_RepositoryId


    _omni_op_d = {"setMode": _0_ICLOCK_PRO.TimeMngr._d_setMode, "getMode": _0_ICLOCK_PRO.TimeMngr._d_getMode, "setDataStreams": _0_ICLOCK_PRO.TimeMngr._d_setDataStreams, "getDataStreams": _0_ICLOCK_PRO.TimeMngr._d_getDataStreams, "setSampleTime": _0_ICLOCK_PRO.TimeMngr._d_setSampleTime, "getSampleTime": _0_ICLOCK_PRO.TimeMngr._d_getSampleTime, "setIntervalMode": _0_ICLOCK_PRO.TimeMngr._d_setIntervalMode, "setPacketMode": _0_ICLOCK_PRO.TimeMngr._d_setPacketMode, "isPacketMode": _0_ICLOCK_PRO.TimeMngr._d_isPacketMode, "step": _0_ICLOCK_PRO.TimeMngr._d_step, "getMinTime": _0_ICLOCK_PRO.TimeMngr._d_getMinTime, "getMaxTime": _0_ICLOCK_PRO.TimeMngr._d_getMaxTime, "getUTC": _0_ICLOCK_PRO.TimeMngr._d_getUTC, "getDeltaTimeToUTC": _0_ICLOCK_PRO.TimeMngr._d_getDeltaTimeToUTC}

TimeMngr._omni_skeleton = TimeMngr
_0_ICLOCK_PRO__POA.TimeMngr = TimeMngr
omniORB.registerSkeleton(TimeMngr._NP_RepositoryId, TimeMngr)
del TimeMngr
__name__ = "ICLOCK_PRO"

# interface TimingServer
_0_ICLOCK_PRO._d_TimingServer = (omniORB.tcInternal.tv_objref, "IDL:ICLOCK_PRO/TimingServer:1.0", "TimingServer")
omniORB.typeMapping["IDL:ICLOCK_PRO/TimingServer:1.0"] = _0_ICLOCK_PRO._d_TimingServer
_0_ICLOCK_PRO.TimingServer = omniORB.newEmptyClass()
class TimingServer (_0_IBASE_IF.Server):
    _NP_RepositoryId = _0_ICLOCK_PRO._d_TimingServer[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ICLOCK_PRO.TimingServer = TimingServer
_0_ICLOCK_PRO._tc_TimingServer = omniORB.tcInternal.createTypeCode(_0_ICLOCK_PRO._d_TimingServer)
omniORB.registerType(TimingServer._NP_RepositoryId, _0_ICLOCK_PRO._d_TimingServer, _0_ICLOCK_PRO._tc_TimingServer)

# TimingServer operations and attributes
TimingServer._d__get_m_timeMngr = ((),(omniORB.typeMapping["IDL:ICLOCK_PRO/TimeMngr:1.0"],),None)

# TimingServer object reference
class _objref_TimingServer (_0_IBASE_IF._objref_Server):
    _NP_RepositoryId = TimingServer._NP_RepositoryId

    def __init__(self, obj):
        _0_IBASE_IF._objref_Server.__init__(self, obj)

    def _get_m_timeMngr(self, *args):
        return self._obj.invoke("_get_m_timeMngr", _0_ICLOCK_PRO.TimingServer._d__get_m_timeMngr, args)

    m_timeMngr = property(_get_m_timeMngr)


omniORB.registerObjref(TimingServer._NP_RepositoryId, _objref_TimingServer)
_0_ICLOCK_PRO._objref_TimingServer = _objref_TimingServer
del TimingServer, _objref_TimingServer

# TimingServer skeleton
__name__ = "ICLOCK_PRO__POA"
class TimingServer (_0_IBASE_IF__POA.Server):
    _NP_RepositoryId = _0_ICLOCK_PRO.TimingServer._NP_RepositoryId


    _omni_op_d = {"_get_m_timeMngr": _0_ICLOCK_PRO.TimingServer._d__get_m_timeMngr}
    _omni_op_d.update(_0_IBASE_IF__POA.Server._omni_op_d)

TimingServer._omni_skeleton = TimingServer
_0_ICLOCK_PRO__POA.TimingServer = TimingServer
omniORB.registerSkeleton(TimingServer._NP_RepositoryId, TimingServer)
del TimingServer
__name__ = "ICLOCK_PRO"

# interface TimingServerMngr
_0_ICLOCK_PRO._d_TimingServerMngr = (omniORB.tcInternal.tv_objref, "IDL:ICLOCK_PRO/TimingServerMngr:1.0", "TimingServerMngr")
omniORB.typeMapping["IDL:ICLOCK_PRO/TimingServerMngr:1.0"] = _0_ICLOCK_PRO._d_TimingServerMngr
_0_ICLOCK_PRO.TimingServerMngr = omniORB.newEmptyClass()
class TimingServerMngr (_0_IBASE_IF.ServerMngr):
    _NP_RepositoryId = _0_ICLOCK_PRO._d_TimingServerMngr[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ICLOCK_PRO.TimingServerMngr = TimingServerMngr
_0_ICLOCK_PRO._tc_TimingServerMngr = omniORB.tcInternal.createTypeCode(_0_ICLOCK_PRO._d_TimingServerMngr)
omniORB.registerType(TimingServerMngr._NP_RepositoryId, _0_ICLOCK_PRO._d_TimingServerMngr, _0_ICLOCK_PRO._tc_TimingServerMngr)

# TimingServerMngr operations and attributes
TimingServerMngr._d_getTimingServer = ((omniORB.tcInternal.tv_boolean, ), (omniORB.typeMapping["IDL:ICLOCK_PRO/TimingServer:1.0"], ), {_0_IBASE.NotFound._NP_RepositoryId: _0_IBASE._d_NotFound})

# TimingServerMngr object reference
class _objref_TimingServerMngr (_0_IBASE_IF._objref_ServerMngr):
    _NP_RepositoryId = TimingServerMngr._NP_RepositoryId

    def __init__(self, obj):
        _0_IBASE_IF._objref_ServerMngr.__init__(self, obj)

    def getTimingServer(self, *args):
        return self._obj.invoke("getTimingServer", _0_ICLOCK_PRO.TimingServerMngr._d_getTimingServer, args)

omniORB.registerObjref(TimingServerMngr._NP_RepositoryId, _objref_TimingServerMngr)
_0_ICLOCK_PRO._objref_TimingServerMngr = _objref_TimingServerMngr
del TimingServerMngr, _objref_TimingServerMngr

# TimingServerMngr skeleton
__name__ = "ICLOCK_PRO__POA"
class TimingServerMngr (_0_IBASE_IF__POA.ServerMngr):
    _NP_RepositoryId = _0_ICLOCK_PRO.TimingServerMngr._NP_RepositoryId


    _omni_op_d = {"getTimingServer": _0_ICLOCK_PRO.TimingServerMngr._d_getTimingServer}
    _omni_op_d.update(_0_IBASE_IF__POA.ServerMngr._omni_op_d)

TimingServerMngr._omni_skeleton = TimingServerMngr
_0_ICLOCK_PRO__POA.TimingServerMngr = TimingServerMngr
omniORB.registerSkeleton(TimingServerMngr._NP_RepositoryId, TimingServerMngr)
del TimingServerMngr
__name__ = "ICLOCK_PRO"

#
# End of module "ICLOCK_PRO"
#
__name__ = "ICLOCK_PRO_idl"

_exported_modules = ( "ICLOCK_PRO", )

# The end.
