# Python stubs generated by omniidl from ICLOCK.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "ICLOCK"
#
__name__ = "ICLOCK"
_0_ICLOCK = omniORB.openModule("ICLOCK", r"ICLOCK.idl")
_0_ICLOCK__POA = omniORB.openModule("ICLOCK__POA", r"ICLOCK.idl")


# typedef ... TimeMode
class TimeMode:
    _NP_RepositoryId = "IDL:ICLOCK/TimeMode:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ICLOCK.TimeMode = TimeMode
_0_ICLOCK._d_TimeMode  = omniORB.tcInternal.tv_char
_0_ICLOCK._ad_TimeMode = (omniORB.tcInternal.tv_alias, TimeMode._NP_RepositoryId, "TimeMode", omniORB.tcInternal.tv_char)
_0_ICLOCK._tc_TimeMode = omniORB.tcInternal.createTypeCode(_0_ICLOCK._ad_TimeMode)
omniORB.registerType(TimeMode._NP_RepositoryId, _0_ICLOCK._ad_TimeMode, _0_ICLOCK._tc_TimeMode)
del TimeMode
_0_ICLOCK.REAL_TIME = "R"
_0_ICLOCK.HISTORY_STOP = "H"
_0_ICLOCK.HISTORY_FORWARD = "F"
_0_ICLOCK.HISTORY_BACKWARD = "B"

# typedef ... TimeState
class TimeState:
    _NP_RepositoryId = "IDL:ICLOCK/TimeState:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ICLOCK.TimeState = TimeState
_0_ICLOCK._d_TimeState  = omniORB.tcInternal.tv_char
_0_ICLOCK._ad_TimeState = (omniORB.tcInternal.tv_alias, TimeState._NP_RepositoryId, "TimeState", omniORB.tcInternal.tv_char)
_0_ICLOCK._tc_TimeState = omniORB.tcInternal.createTypeCode(_0_ICLOCK._ad_TimeState)
omniORB.registerType(TimeState._NP_RepositoryId, _0_ICLOCK._ad_TimeState, _0_ICLOCK._tc_TimeState)
del TimeState
_0_ICLOCK.OK = "O"
_0_ICLOCK.TOO_EARLY = "E"
_0_ICLOCK.TOO_LATE = "L"
_0_ICLOCK.INVALID = "I"
_0_ICLOCK.TOO_MANY_STREAMS = "T"

# exception NotPossible
_0_ICLOCK.NotPossible = omniORB.newEmptyClass()
class NotPossible (CORBA.UserException):
    _NP_RepositoryId = "IDL:ICLOCK/NotPossible:1.0"

    def __init__(self, m_reason):
        CORBA.UserException.__init__(self, m_reason)
        self.m_reason = m_reason

_0_ICLOCK.NotPossible = NotPossible
_0_ICLOCK._d_NotPossible  = (omniORB.tcInternal.tv_except, NotPossible, NotPossible._NP_RepositoryId, "NotPossible", "m_reason", omniORB.typeMapping["IDL:ICLOCK/TimeState:1.0"])
_0_ICLOCK._tc_NotPossible = omniORB.tcInternal.createTypeCode(_0_ICLOCK._d_NotPossible)
omniORB.registerType(NotPossible._NP_RepositoryId, _0_ICLOCK._d_NotPossible, _0_ICLOCK._tc_NotPossible)
del NotPossible

#
# End of module "ICLOCK"
#
__name__ = "ICLOCK_idl"

_exported_modules = ( "ICLOCK", )

# The end.
