# Python stubs generated by omniidl from ITM_INJ.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


# #include "IBASE.idl"
import IBASE_idl
_0_IBASE = omniORB.openModule("IBASE")
_0_IBASE__POA = omniORB.openModule("IBASE__POA")

# #include "ITM.idl"
import ITM_idl
_0_ITM = omniORB.openModule("ITM")
_0_ITM__POA = omniORB.openModule("ITM__POA")

#
# Start of module "ITM_INJ"
#
__name__ = "ITM_INJ"
_0_ITM_INJ = omniORB.openModule("ITM_INJ", r"ITM_INJ.idl")
_0_ITM_INJ__POA = omniORB.openModule("ITM_INJ__POA", r"ITM_INJ.idl")


# interface ParamInjectMngr
_0_ITM_INJ._d_ParamInjectMngr = (omniORB.tcInternal.tv_objref, "IDL:ITM_INJ/ParamInjectMngr:1.0", "ParamInjectMngr")
omniORB.typeMapping["IDL:ITM_INJ/ParamInjectMngr:1.0"] = _0_ITM_INJ._d_ParamInjectMngr
_0_ITM_INJ.ParamInjectMngr = omniORB.newEmptyClass()
class ParamInjectMngr :
    _NP_RepositoryId = _0_ITM_INJ._d_ParamInjectMngr[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil

    ServiceName = "TM_INJ_001"


_0_ITM_INJ.ParamInjectMngr = ParamInjectMngr
_0_ITM_INJ._tc_ParamInjectMngr = omniORB.tcInternal.createTypeCode(_0_ITM_INJ._d_ParamInjectMngr)
omniORB.registerType(ParamInjectMngr._NP_RepositoryId, _0_ITM_INJ._d_ParamInjectMngr, _0_ITM_INJ._tc_ParamInjectMngr)

# ParamInjectMngr operations and attributes
ParamInjectMngr._d_getUTC = ((), (omniORB.typeMapping["IDL:IBASE/Time:1.0"], ), None)
ParamInjectMngr._d_getDeltaTimeToUTC = ((), (omniORB.typeMapping["IDL:IBASE/Time:1.0"], ), None)
ParamInjectMngr._d_getDefaultDataStream = ((), (omniORB.tcInternal.tv_long, ), None)
ParamInjectMngr._d_getDefaultSpacecraftID = ((), ((omniORB.tcInternal.tv_string,0), ), None)
ParamInjectMngr._d_injectParameter = ((omniORB.typeMapping["IDL:ITM/InjectParam:1.0"], (omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:IBASE/Time:1.0"], omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), {_0_IBASE.NotFound._NP_RepositoryId: _0_IBASE._d_NotFound, _0_IBASE.NotProcessed._NP_RepositoryId: _0_IBASE._d_NotProcessed})
ParamInjectMngr._d_injectParameterWithDefaults = ((omniORB.typeMapping["IDL:ITM/InjectParam:1.0"], (omniORB.tcInternal.tv_string,0)), (), {_0_IBASE.NotFound._NP_RepositoryId: _0_IBASE._d_NotFound, _0_IBASE.NotProcessed._NP_RepositoryId: _0_IBASE._d_NotProcessed})
ParamInjectMngr._d_injectParameters = ((omniORB.typeMapping["IDL:ITM/InjectParams:1.0"], (omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:IBASE/Time:1.0"], omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), {_0_IBASE.NotFound._NP_RepositoryId: _0_IBASE._d_NotFound, _0_IBASE.NotProcessed._NP_RepositoryId: _0_IBASE._d_NotProcessed})
ParamInjectMngr._d_injectParametersWithDefaults = ((omniORB.typeMapping["IDL:ITM/InjectParams:1.0"], (omniORB.tcInternal.tv_string,0)), (), {_0_IBASE.NotFound._NP_RepositoryId: _0_IBASE._d_NotFound, _0_IBASE.NotProcessed._NP_RepositoryId: _0_IBASE._d_NotProcessed})

# ParamInjectMngr object reference
class _objref_ParamInjectMngr (CORBA.Object):
    _NP_RepositoryId = ParamInjectMngr._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def getUTC(self, *args):
        return self._obj.invoke("getUTC", _0_ITM_INJ.ParamInjectMngr._d_getUTC, args)

    def getDeltaTimeToUTC(self, *args):
        return self._obj.invoke("getDeltaTimeToUTC", _0_ITM_INJ.ParamInjectMngr._d_getDeltaTimeToUTC, args)

    def getDefaultDataStream(self, *args):
        return self._obj.invoke("getDefaultDataStream", _0_ITM_INJ.ParamInjectMngr._d_getDefaultDataStream, args)

    def getDefaultSpacecraftID(self, *args):
        return self._obj.invoke("getDefaultSpacecraftID", _0_ITM_INJ.ParamInjectMngr._d_getDefaultSpacecraftID, args)

    def injectParameter(self, *args):
        return self._obj.invoke("injectParameter", _0_ITM_INJ.ParamInjectMngr._d_injectParameter, args)

    def injectParameterWithDefaults(self, *args):
        return self._obj.invoke("injectParameterWithDefaults", _0_ITM_INJ.ParamInjectMngr._d_injectParameterWithDefaults, args)

    def injectParameters(self, *args):
        return self._obj.invoke("injectParameters", _0_ITM_INJ.ParamInjectMngr._d_injectParameters, args)

    def injectParametersWithDefaults(self, *args):
        return self._obj.invoke("injectParametersWithDefaults", _0_ITM_INJ.ParamInjectMngr._d_injectParametersWithDefaults, args)

omniORB.registerObjref(ParamInjectMngr._NP_RepositoryId, _objref_ParamInjectMngr)
_0_ITM_INJ._objref_ParamInjectMngr = _objref_ParamInjectMngr
del ParamInjectMngr, _objref_ParamInjectMngr

# ParamInjectMngr skeleton
__name__ = "ITM_INJ__POA"
class ParamInjectMngr (PortableServer.Servant):
    _NP_RepositoryId = _0_ITM_INJ.ParamInjectMngr._NP_RepositoryId


    _omni_op_d = {"getUTC": _0_ITM_INJ.ParamInjectMngr._d_getUTC, "getDeltaTimeToUTC": _0_ITM_INJ.ParamInjectMngr._d_getDeltaTimeToUTC, "getDefaultDataStream": _0_ITM_INJ.ParamInjectMngr._d_getDefaultDataStream, "getDefaultSpacecraftID": _0_ITM_INJ.ParamInjectMngr._d_getDefaultSpacecraftID, "injectParameter": _0_ITM_INJ.ParamInjectMngr._d_injectParameter, "injectParameterWithDefaults": _0_ITM_INJ.ParamInjectMngr._d_injectParameterWithDefaults, "injectParameters": _0_ITM_INJ.ParamInjectMngr._d_injectParameters, "injectParametersWithDefaults": _0_ITM_INJ.ParamInjectMngr._d_injectParametersWithDefaults}

ParamInjectMngr._omni_skeleton = ParamInjectMngr
_0_ITM_INJ__POA.ParamInjectMngr = ParamInjectMngr
omniORB.registerSkeleton(ParamInjectMngr._NP_RepositoryId, ParamInjectMngr)
del ParamInjectMngr
__name__ = "ITM_INJ"

#
# End of module "ITM_INJ"
#
__name__ = "ITM_INJ_idl"

_exported_modules = ( "ITM_INJ", )

# The end.
