# Python stubs generated by omniidl from ITMP.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


# #include "IBASE.idl"
import IBASE_idl
_0_IBASE = omniORB.openModule("IBASE")
_0_IBASE__POA = omniORB.openModule("IBASE__POA")

#
# Start of module "ITMP"
#
__name__ = "ITMP"
_0_ITMP = omniORB.openModule("ITMP", r"ITMP.idl")
_0_ITMP__POA = omniORB.openModule("ITMP__POA", r"ITMP.idl")


# typedef ... UnsignedLongs
class UnsignedLongs:
    _NP_RepositoryId = "IDL:ITMP/UnsignedLongs:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ITMP.UnsignedLongs = UnsignedLongs
_0_ITMP._d_UnsignedLongs  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_ulong, 0)
_0_ITMP._ad_UnsignedLongs = (omniORB.tcInternal.tv_alias, UnsignedLongs._NP_RepositoryId, "UnsignedLongs", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_ulong, 0))
_0_ITMP._tc_UnsignedLongs = omniORB.tcInternal.createTypeCode(_0_ITMP._ad_UnsignedLongs)
omniORB.registerType(UnsignedLongs._NP_RepositoryId, _0_ITMP._ad_UnsignedLongs, _0_ITMP._tc_UnsignedLongs)
del UnsignedLongs

# typedef ... UnsignedShorts
class UnsignedShorts:
    _NP_RepositoryId = "IDL:ITMP/UnsignedShorts:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ITMP.UnsignedShorts = UnsignedShorts
_0_ITMP._d_UnsignedShorts  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_ushort, 0)
_0_ITMP._ad_UnsignedShorts = (omniORB.tcInternal.tv_alias, UnsignedShorts._NP_RepositoryId, "UnsignedShorts", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_ushort, 0))
_0_ITMP._tc_UnsignedShorts = omniORB.tcInternal.createTypeCode(_0_ITMP._ad_UnsignedShorts)
omniORB.registerType(UnsignedShorts._NP_RepositoryId, _0_ITMP._ad_UnsignedShorts, _0_ITMP._tc_UnsignedShorts)
del UnsignedShorts

# typedef ... TimeStampType
class TimeStampType:
    _NP_RepositoryId = "IDL:ITMP/TimeStampType:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ITMP.TimeStampType = TimeStampType
_0_ITMP._d_TimeStampType  = omniORB.tcInternal.tv_char
_0_ITMP._ad_TimeStampType = (omniORB.tcInternal.tv_alias, TimeStampType._NP_RepositoryId, "TimeStampType", omniORB.tcInternal.tv_char)
_0_ITMP._tc_TimeStampType = omniORB.tcInternal.createTypeCode(_0_ITMP._ad_TimeStampType)
omniORB.registerType(TimeStampType._NP_RepositoryId, _0_ITMP._ad_TimeStampType, _0_ITMP._tc_TimeStampType)
del TimeStampType
_0_ITMP.TST_PacketReception = "0"
_0_ITMP.TST_FrameTransmission = "1"
_0_ITMP.TST_PacketGeneration = "2"

# typedef ... TimeQualityFlag
class TimeQualityFlag:
    _NP_RepositoryId = "IDL:ITMP/TimeQualityFlag:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ITMP.TimeQualityFlag = TimeQualityFlag
_0_ITMP._d_TimeQualityFlag  = omniORB.tcInternal.tv_char
_0_ITMP._ad_TimeQualityFlag = (omniORB.tcInternal.tv_alias, TimeQualityFlag._NP_RepositoryId, "TimeQualityFlag", omniORB.tcInternal.tv_char)
_0_ITMP._tc_TimeQualityFlag = omniORB.tcInternal.createTypeCode(_0_ITMP._ad_TimeQualityFlag)
omniORB.registerType(TimeQualityFlag._NP_RepositoryId, _0_ITMP._ad_TimeQualityFlag, _0_ITMP._tc_TimeQualityFlag)
del TimeQualityFlag
_0_ITMP.TQF_Null = "N"
_0_ITMP.TQF_Good = "G"
_0_ITMP.TQF_Inaccurate = "I"
_0_ITMP.TQF_Bad = "B"

# typedef ... QualDataUnitType
class QualDataUnitType:
    _NP_RepositoryId = "IDL:ITMP/QualDataUnitType:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ITMP.QualDataUnitType = QualDataUnitType
_0_ITMP._d_QualDataUnitType  = omniORB.tcInternal.tv_char
_0_ITMP._ad_QualDataUnitType = (omniORB.tcInternal.tv_alias, QualDataUnitType._NP_RepositoryId, "QualDataUnitType", omniORB.tcInternal.tv_char)
_0_ITMP._tc_QualDataUnitType = omniORB.tcInternal.createTypeCode(_0_ITMP._ad_QualDataUnitType)
omniORB.registerType(QualDataUnitType._NP_RepositoryId, _0_ITMP._ad_QualDataUnitType, _0_ITMP._tc_QualDataUnitType)
del QualDataUnitType
_0_ITMP.QDUT_NO_QDU = "U"
_0_ITMP.QDUT_GOOD_TF_QDU = "Q"
_0_ITMP.QDUT_BAD_TF_QDU = "B"
_0_ITMP.QDUT_IDLE_TF_QDU = "I"
_0_ITMP.QDUT_GOOD_SP_QDU = "G"
_0_ITMP.QDUT_BAD_SP_QDU = "A"
_0_ITMP.QDUT_IDLE_SP_QDU = "D"
_0_ITMP.QDUT_UNKN_SP_QDU = "N"
_0_ITMP.QDUT_TIME_SP_QDU = "T"
_0_ITMP.QDUT_CLCW_PKT_QDU = "C"
_0_ITMP.QDUT_UDC_PKT_QDU = "P"
_0_ITMP.QDUT_SCC_PKT_QDU = "S"
_0_ITMP.QDUT_MISC_PKT_QDU = "M"
_0_ITMP.QDUT_MIB_PKT_QDU = "K"
_0_ITMP.QDUT_SPPG_PKT_QDU = "E"
_0_ITMP.QDUT_SPIDV_PKT_QDU = "V"
_0_ITMP.QDUT_TPKT_PKT_QDU = "F"
_0_ITMP.QDUT_EXSRC_PKT_QDU = "X"
_0_ITMP.QDUT_RES1_PKT_QDU = "1"
_0_ITMP.QDUT_RES2_PKT_QDU = "2"

# struct TMpacketAttributes
_0_ITMP.TMpacketAttributes = omniORB.newEmptyClass()
class TMpacketAttributes (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ITMP/TMpacketAttributes:1.0"

    def __init__(self, m_pktDetailsFlag, m_mnemo, m_filingTime, m_createTime, m_vcId, m_pusApId, m_pusSrcSeqCnt, m_pusSrvcType, m_pusSrvcSubType, m_pi1Field, m_pi2Field, m_streamId, m_filingKey, m_gsId, m_timeStampType, m_timeQualityFlag, m_filingFlag, m_distributionFlag, m_packetDescription, m_simulationFlag, m_spaceCraftId, m_sleID, m_occID, m_qualDataUnitType, m_tpsd, m_seqCounter, m_timeField, m_interval, m_eventFlag, m_checkFlag):
        self.m_pktDetailsFlag = m_pktDetailsFlag
        self.m_mnemo = m_mnemo
        self.m_filingTime = m_filingTime
        self.m_createTime = m_createTime
        self.m_vcId = m_vcId
        self.m_pusApId = m_pusApId
        self.m_pusSrcSeqCnt = m_pusSrcSeqCnt
        self.m_pusSrvcType = m_pusSrvcType
        self.m_pusSrvcSubType = m_pusSrvcSubType
        self.m_pi1Field = m_pi1Field
        self.m_pi2Field = m_pi2Field
        self.m_streamId = m_streamId
        self.m_filingKey = m_filingKey
        self.m_gsId = m_gsId
        self.m_timeStampType = m_timeStampType
        self.m_timeQualityFlag = m_timeQualityFlag
        self.m_filingFlag = m_filingFlag
        self.m_distributionFlag = m_distributionFlag
        self.m_packetDescription = m_packetDescription
        self.m_simulationFlag = m_simulationFlag
        self.m_spaceCraftId = m_spaceCraftId
        self.m_sleID = m_sleID
        self.m_occID = m_occID
        self.m_qualDataUnitType = m_qualDataUnitType
        self.m_tpsd = m_tpsd
        self.m_seqCounter = m_seqCounter
        self.m_timeField = m_timeField
        self.m_interval = m_interval
        self.m_eventFlag = m_eventFlag
        self.m_checkFlag = m_checkFlag

_0_ITMP.TMpacketAttributes = TMpacketAttributes
_0_ITMP._d_TMpacketAttributes  = (omniORB.tcInternal.tv_struct, TMpacketAttributes, TMpacketAttributes._NP_RepositoryId, "TMpacketAttributes", "m_pktDetailsFlag", omniORB.tcInternal.tv_boolean, "m_mnemo", (omniORB.tcInternal.tv_string,0), "m_filingTime", omniORB.typeMapping["IDL:IBASE/Time:1.0"], "m_createTime", omniORB.typeMapping["IDL:IBASE/Time:1.0"], "m_vcId", omniORB.tcInternal.tv_octet, "m_pusApId", omniORB.tcInternal.tv_ushort, "m_pusSrcSeqCnt", omniORB.tcInternal.tv_ushort, "m_pusSrvcType", omniORB.tcInternal.tv_ushort, "m_pusSrvcSubType", omniORB.tcInternal.tv_ushort, "m_pi1Field", omniORB.tcInternal.tv_ulong, "m_pi2Field", omniORB.tcInternal.tv_ulong, "m_streamId", omniORB.tcInternal.tv_ushort, "m_filingKey", omniORB.tcInternal.tv_ulong, "m_gsId", omniORB.tcInternal.tv_ushort, "m_timeStampType", omniORB.typeMapping["IDL:ITMP/TimeStampType:1.0"], "m_timeQualityFlag", omniORB.typeMapping["IDL:ITMP/TimeQualityFlag:1.0"], "m_filingFlag", omniORB.tcInternal.tv_boolean, "m_distributionFlag", omniORB.tcInternal.tv_boolean, "m_packetDescription", (omniORB.tcInternal.tv_string,0), "m_simulationFlag", omniORB.tcInternal.tv_boolean, "m_spaceCraftId", omniORB.tcInternal.tv_ushort, "m_sleID", omniORB.tcInternal.tv_octet, "m_occID", omniORB.tcInternal.tv_octet, "m_qualDataUnitType", omniORB.typeMapping["IDL:ITMP/QualDataUnitType:1.0"], "m_tpsd", omniORB.tcInternal.tv_long, "m_seqCounter", omniORB.tcInternal.tv_ulong, "m_timeField", omniORB.tcInternal.tv_boolean, "m_interval", omniORB.tcInternal.tv_long, "m_eventFlag", (omniORB.tcInternal.tv_string,0), "m_checkFlag", omniORB.tcInternal.tv_octet)
_0_ITMP._tc_TMpacketAttributes = omniORB.tcInternal.createTypeCode(_0_ITMP._d_TMpacketAttributes)
omniORB.registerType(TMpacketAttributes._NP_RepositoryId, _0_ITMP._d_TMpacketAttributes, _0_ITMP._tc_TMpacketAttributes)
del TMpacketAttributes

# struct TMpacketParam
_0_ITMP.TMpacketParam = omniORB.newEmptyClass()
class TMpacketParam (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ITMP/TMpacketParam:1.0"

    def __init__(self, m_name, m_description, m_value, m_unit, m_form):
        self.m_name = m_name
        self.m_description = m_description
        self.m_value = m_value
        self.m_unit = m_unit
        self.m_form = m_form

_0_ITMP.TMpacketParam = TMpacketParam
_0_ITMP._d_TMpacketParam  = (omniORB.tcInternal.tv_struct, TMpacketParam, TMpacketParam._NP_RepositoryId, "TMpacketParam", "m_name", (omniORB.tcInternal.tv_string,0), "m_description", (omniORB.tcInternal.tv_string,0), "m_value", (omniORB.tcInternal.tv_string,0), "m_unit", (omniORB.tcInternal.tv_string,0), "m_form", omniORB.typeMapping["IDL:IBASE/Radix:1.0"])
_0_ITMP._tc_TMpacketParam = omniORB.tcInternal.createTypeCode(_0_ITMP._d_TMpacketParam)
omniORB.registerType(TMpacketParam._NP_RepositoryId, _0_ITMP._d_TMpacketParam, _0_ITMP._tc_TMpacketParam)
del TMpacketParam

# typedef ... TMpacketParams
class TMpacketParams:
    _NP_RepositoryId = "IDL:ITMP/TMpacketParams:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ITMP.TMpacketParams = TMpacketParams
_0_ITMP._d_TMpacketParams  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMP/TMpacketParam:1.0"], 0)
_0_ITMP._ad_TMpacketParams = (omniORB.tcInternal.tv_alias, TMpacketParams._NP_RepositoryId, "TMpacketParams", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMP/TMpacketParam:1.0"], 0))
_0_ITMP._tc_TMpacketParams = omniORB.tcInternal.createTypeCode(_0_ITMP._ad_TMpacketParams)
omniORB.registerType(TMpacketParams._NP_RepositoryId, _0_ITMP._ad_TMpacketParams, _0_ITMP._tc_TMpacketParams)
del TMpacketParams

# struct TMpacketNotifyData
_0_ITMP.TMpacketNotifyData = omniORB.newEmptyClass()
class TMpacketNotifyData (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ITMP/TMpacketNotifyData:1.0"

    def __init__(self, m_pktAttributes, m_pktHeaderRawData, m_pktBodyRawData, m_pktParams):
        self.m_pktAttributes = m_pktAttributes
        self.m_pktHeaderRawData = m_pktHeaderRawData
        self.m_pktBodyRawData = m_pktBodyRawData
        self.m_pktParams = m_pktParams

_0_ITMP.TMpacketNotifyData = TMpacketNotifyData
_0_ITMP._d_TMpacketNotifyData  = (omniORB.tcInternal.tv_struct, TMpacketNotifyData, TMpacketNotifyData._NP_RepositoryId, "TMpacketNotifyData", "m_pktAttributes", omniORB.typeMapping["IDL:ITMP/TMpacketAttributes:1.0"], "m_pktHeaderRawData", omniORB.typeMapping["IDL:IBASE/ByteString:1.0"], "m_pktBodyRawData", omniORB.typeMapping["IDL:IBASE/ByteString:1.0"], "m_pktParams", omniORB.typeMapping["IDL:ITMP/TMpacketParams:1.0"])
_0_ITMP._tc_TMpacketNotifyData = omniORB.tcInternal.createTypeCode(_0_ITMP._d_TMpacketNotifyData)
omniORB.registerType(TMpacketNotifyData._NP_RepositoryId, _0_ITMP._d_TMpacketNotifyData, _0_ITMP._tc_TMpacketNotifyData)
del TMpacketNotifyData

# typedef ... TMpacketNotifyDatas
class TMpacketNotifyDatas:
    _NP_RepositoryId = "IDL:ITMP/TMpacketNotifyDatas:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ITMP.TMpacketNotifyDatas = TMpacketNotifyDatas
_0_ITMP._d_TMpacketNotifyDatas  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMP/TMpacketNotifyData:1.0"], 0)
_0_ITMP._ad_TMpacketNotifyDatas = (omniORB.tcInternal.tv_alias, TMpacketNotifyDatas._NP_RepositoryId, "TMpacketNotifyDatas", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMP/TMpacketNotifyData:1.0"], 0))
_0_ITMP._tc_TMpacketNotifyDatas = omniORB.tcInternal.createTypeCode(_0_ITMP._ad_TMpacketNotifyDatas)
omniORB.registerType(TMpacketNotifyDatas._NP_RepositoryId, _0_ITMP._ad_TMpacketNotifyDatas, _0_ITMP._tc_TMpacketNotifyDatas)
del TMpacketNotifyDatas

# struct TMpacketFilter
_0_ITMP.TMpacketFilter = omniORB.newEmptyClass()
class TMpacketFilter (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ITMP/TMpacketFilter:1.0"

    def __init__(self, m_streamIds, m_apIds, m_filingKeys):
        self.m_streamIds = m_streamIds
        self.m_apIds = m_apIds
        self.m_filingKeys = m_filingKeys

_0_ITMP.TMpacketFilter = TMpacketFilter
_0_ITMP._d_TMpacketFilter  = (omniORB.tcInternal.tv_struct, TMpacketFilter, TMpacketFilter._NP_RepositoryId, "TMpacketFilter", "m_streamIds", omniORB.typeMapping["IDL:ITMP/UnsignedShorts:1.0"], "m_apIds", omniORB.typeMapping["IDL:ITMP/UnsignedShorts:1.0"], "m_filingKeys", omniORB.typeMapping["IDL:ITMP/UnsignedLongs:1.0"])
_0_ITMP._tc_TMpacketFilter = omniORB.tcInternal.createTypeCode(_0_ITMP._d_TMpacketFilter)
omniORB.registerType(TMpacketFilter._NP_RepositoryId, _0_ITMP._d_TMpacketFilter, _0_ITMP._tc_TMpacketFilter)
del TMpacketFilter

# struct TransmissionFilter
_0_ITMP.TransmissionFilter = omniORB.newEmptyClass()
class TransmissionFilter (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ITMP/TransmissionFilter:1.0"

    def __init__(self, m_transmitPacketHeaderRawData, m_transmitPacketBodyRawData, m_transmitParameters):
        self.m_transmitPacketHeaderRawData = m_transmitPacketHeaderRawData
        self.m_transmitPacketBodyRawData = m_transmitPacketBodyRawData
        self.m_transmitParameters = m_transmitParameters

_0_ITMP.TransmissionFilter = TransmissionFilter
_0_ITMP._d_TransmissionFilter  = (omniORB.tcInternal.tv_struct, TransmissionFilter, TransmissionFilter._NP_RepositoryId, "TransmissionFilter", "m_transmitPacketHeaderRawData", omniORB.tcInternal.tv_boolean, "m_transmitPacketBodyRawData", omniORB.tcInternal.tv_boolean, "m_transmitParameters", omniORB.tcInternal.tv_boolean)
_0_ITMP._tc_TransmissionFilter = omniORB.tcInternal.createTypeCode(_0_ITMP._d_TransmissionFilter)
omniORB.registerType(TransmissionFilter._NP_RepositoryId, _0_ITMP._d_TransmissionFilter, _0_ITMP._tc_TransmissionFilter)
del TransmissionFilter

#
# End of module "ITMP"
#
__name__ = "ITMP_idl"

_exported_modules = ( "ITMP", )

# The end.
