# Python stubs generated by omniidl from ITMSET_PRO.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


# #include "IBASE.idl"
import IBASE_idl
_0_IBASE = omniORB.openModule("IBASE")
_0_IBASE__POA = omniORB.openModule("IBASE__POA")

# #include "IMIB.idl"
import IMIB_idl
_0_IMIB = omniORB.openModule("IMIB")
_0_IMIB__POA = omniORB.openModule("IMIB__POA")

# #include "ITM.idl"
import ITM_idl
_0_ITM = omniORB.openModule("ITM")
_0_ITM__POA = omniORB.openModule("ITM__POA")

# #include "ITMSET.idl"
import ITMSET_idl
_0_ITMSET = omniORB.openModule("ITMSET")
_0_ITMSET__POA = omniORB.openModule("ITMSET__POA")

# #include "ICLOCK.idl"
import ICLOCK_idl
_0_ICLOCK = omniORB.openModule("ICLOCK")
_0_ICLOCK__POA = omniORB.openModule("ICLOCK__POA")

# #include "IBASE_IF.idl"
import IBASE_IF_idl
_0_IBASE_IF = omniORB.openModule("IBASE_IF")
_0_IBASE_IF__POA = omniORB.openModule("IBASE_IF__POA")

#
# Start of module "ITMSET_PRO"
#
__name__ = "ITMSET_PRO"
_0_ITMSET_PRO = omniORB.openModule("ITMSET_PRO", r"ITMSET_PRO.idl")
_0_ITMSET_PRO__POA = omniORB.openModule("ITMSET_PRO__POA", r"ITMSET_PRO.idl")


# forward interface SetMngrView;
_0_ITMSET_PRO._d_SetMngrView = (omniORB.tcInternal.tv_objref, "IDL:ITMSET_PRO/SetMngrView:1.0", "SetMngrView")
omniORB.typeMapping["IDL:ITMSET_PRO/SetMngrView:1.0"] = _0_ITMSET_PRO._d_SetMngrView

# interface SetMngr
_0_ITMSET_PRO._d_SetMngr = (omniORB.tcInternal.tv_objref, "IDL:ITMSET_PRO/SetMngr:1.0", "SetMngr")
omniORB.typeMapping["IDL:ITMSET_PRO/SetMngr:1.0"] = _0_ITMSET_PRO._d_SetMngr
_0_ITMSET_PRO.SetMngr = omniORB.newEmptyClass()
class SetMngr (_0_IBASE_IF.Model):
    _NP_RepositoryId = _0_ITMSET_PRO._d_SetMngr[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ITMSET_PRO.SetMngr = SetMngr
_0_ITMSET_PRO._tc_SetMngr = omniORB.tcInternal.createTypeCode(_0_ITMSET_PRO._d_SetMngr)
omniORB.registerType(SetMngr._NP_RepositoryId, _0_ITMSET_PRO._d_SetMngr, _0_ITMSET_PRO._tc_SetMngr)

# SetMngr operations and attributes
SetMngr._d_registerSetView = ((omniORB.typeMapping["IDL:ITMSET_PRO/SetMngrView:1.0"], omniORB.typeMapping["IDL:ITMSET/TransmissionFilter:1.0"]), (omniORB.tcInternal.tv_long, ), None)
SetMngr._d_unregisterSetView = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_boolean, ), None)
SetMngr._d_registerSet = ((omniORB.tcInternal.tv_long, omniORB.typeMapping["IDL:ITMSET/SetRegisterCrit:1.0"]), (omniORB.tcInternal.tv_boolean, ), None)
SetMngr._d_registerSetInit = ((omniORB.tcInternal.tv_long, omniORB.typeMapping["IDL:ITMSET/SetRegisterCrit:1.0"]), (omniORB.typeMapping["IDL:ITMSET/ClientNotifyData:1.0"], ), {_0_IBASE.NotProcessed._NP_RepositoryId: _0_IBASE._d_NotProcessed})
SetMngr._d_unregisterSet = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_boolean, ), None)
SetMngr._d_registerParamInSet = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, omniORB.typeMapping["IDL:ITMSET/ParamRegisterCrit:1.0"]), (omniORB.tcInternal.tv_boolean, ), None)
SetMngr._d_unregisterParamInSet = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_boolean, ), None)
SetMngr._d_modifyTransmissionFilter = ((omniORB.tcInternal.tv_long, omniORB.typeMapping["IDL:ITMSET/TransmissionFilter:1.0"]), (omniORB.tcInternal.tv_boolean, ), None)
SetMngr._d_getFullData = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:ITMSET/ClientNotifyData:1.0"], ), {_0_ICLOCK.NotPossible._NP_RepositoryId: _0_ICLOCK._d_NotPossible})
SetMngr._d_getNextData = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:ITMSET/ClientNotifyData:1.0"], ), {_0_ICLOCK.NotPossible._NP_RepositoryId: _0_ICLOCK._d_NotPossible})

# SetMngr object reference
class _objref_SetMngr (_0_IBASE_IF._objref_Model):
    _NP_RepositoryId = SetMngr._NP_RepositoryId

    def __init__(self, obj):
        _0_IBASE_IF._objref_Model.__init__(self, obj)

    def registerSetView(self, *args):
        return self._obj.invoke("registerSetView", _0_ITMSET_PRO.SetMngr._d_registerSetView, args)

    def unregisterSetView(self, *args):
        return self._obj.invoke("unregisterSetView", _0_ITMSET_PRO.SetMngr._d_unregisterSetView, args)

    def registerSet(self, *args):
        return self._obj.invoke("registerSet", _0_ITMSET_PRO.SetMngr._d_registerSet, args)

    def registerSetInit(self, *args):
        return self._obj.invoke("registerSetInit", _0_ITMSET_PRO.SetMngr._d_registerSetInit, args)

    def unregisterSet(self, *args):
        return self._obj.invoke("unregisterSet", _0_ITMSET_PRO.SetMngr._d_unregisterSet, args)

    def registerParamInSet(self, *args):
        return self._obj.invoke("registerParamInSet", _0_ITMSET_PRO.SetMngr._d_registerParamInSet, args)

    def unregisterParamInSet(self, *args):
        return self._obj.invoke("unregisterParamInSet", _0_ITMSET_PRO.SetMngr._d_unregisterParamInSet, args)

    def modifyTransmissionFilter(self, *args):
        return self._obj.invoke("modifyTransmissionFilter", _0_ITMSET_PRO.SetMngr._d_modifyTransmissionFilter, args)

    def getFullData(self, *args):
        return self._obj.invoke("getFullData", _0_ITMSET_PRO.SetMngr._d_getFullData, args)

    def getNextData(self, *args):
        return self._obj.invoke("getNextData", _0_ITMSET_PRO.SetMngr._d_getNextData, args)

omniORB.registerObjref(SetMngr._NP_RepositoryId, _objref_SetMngr)
_0_ITMSET_PRO._objref_SetMngr = _objref_SetMngr
del SetMngr, _objref_SetMngr

# SetMngr skeleton
__name__ = "ITMSET_PRO__POA"
class SetMngr (_0_IBASE_IF__POA.Model):
    _NP_RepositoryId = _0_ITMSET_PRO.SetMngr._NP_RepositoryId


    _omni_op_d = {"registerSetView": _0_ITMSET_PRO.SetMngr._d_registerSetView, "unregisterSetView": _0_ITMSET_PRO.SetMngr._d_unregisterSetView, "registerSet": _0_ITMSET_PRO.SetMngr._d_registerSet, "registerSetInit": _0_ITMSET_PRO.SetMngr._d_registerSetInit, "unregisterSet": _0_ITMSET_PRO.SetMngr._d_unregisterSet, "registerParamInSet": _0_ITMSET_PRO.SetMngr._d_registerParamInSet, "unregisterParamInSet": _0_ITMSET_PRO.SetMngr._d_unregisterParamInSet, "modifyTransmissionFilter": _0_ITMSET_PRO.SetMngr._d_modifyTransmissionFilter, "getFullData": _0_ITMSET_PRO.SetMngr._d_getFullData, "getNextData": _0_ITMSET_PRO.SetMngr._d_getNextData}
    _omni_op_d.update(_0_IBASE_IF__POA.Model._omni_op_d)

SetMngr._omni_skeleton = SetMngr
_0_ITMSET_PRO__POA.SetMngr = SetMngr
omniORB.registerSkeleton(SetMngr._NP_RepositoryId, SetMngr)
del SetMngr
__name__ = "ITMSET_PRO"

# interface SetMngrView
_0_ITMSET_PRO._d_SetMngrView = (omniORB.tcInternal.tv_objref, "IDL:ITMSET_PRO/SetMngrView:1.0", "SetMngrView")
omniORB.typeMapping["IDL:ITMSET_PRO/SetMngrView:1.0"] = _0_ITMSET_PRO._d_SetMngrView
_0_ITMSET_PRO.SetMngrView = omniORB.newEmptyClass()
class SetMngrView (_0_IBASE_IF.View):
    _NP_RepositoryId = _0_ITMSET_PRO._d_SetMngrView[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ITMSET_PRO.SetMngrView = SetMngrView
_0_ITMSET_PRO._tc_SetMngrView = omniORB.tcInternal.createTypeCode(_0_ITMSET_PRO._d_SetMngrView)
omniORB.registerType(SetMngrView._NP_RepositoryId, _0_ITMSET_PRO._d_SetMngrView, _0_ITMSET_PRO._tc_SetMngrView)

# SetMngrView operations and attributes
SetMngrView._d_notifySet = ((omniORB.typeMapping["IDL:ITMSET/ClientNotifyData:1.0"], ), (), None)

# SetMngrView object reference
class _objref_SetMngrView (_0_IBASE_IF._objref_View):
    _NP_RepositoryId = SetMngrView._NP_RepositoryId

    def __init__(self, obj):
        _0_IBASE_IF._objref_View.__init__(self, obj)

    def notifySet(self, *args):
        return self._obj.invoke("notifySet", _0_ITMSET_PRO.SetMngrView._d_notifySet, args)

omniORB.registerObjref(SetMngrView._NP_RepositoryId, _objref_SetMngrView)
_0_ITMSET_PRO._objref_SetMngrView = _objref_SetMngrView
del SetMngrView, _objref_SetMngrView

# SetMngrView skeleton
__name__ = "ITMSET_PRO__POA"
class SetMngrView (_0_IBASE_IF__POA.View):
    _NP_RepositoryId = _0_ITMSET_PRO.SetMngrView._NP_RepositoryId


    _omni_op_d = {"notifySet": _0_ITMSET_PRO.SetMngrView._d_notifySet}
    _omni_op_d.update(_0_IBASE_IF__POA.View._omni_op_d)

SetMngrView._omni_skeleton = SetMngrView
_0_ITMSET_PRO__POA.SetMngrView = SetMngrView
omniORB.registerSkeleton(SetMngrView._NP_RepositoryId, SetMngrView)
del SetMngrView
__name__ = "ITMSET_PRO"

#
# End of module "ITMSET_PRO"
#
__name__ = "ITMSET_PRO_idl"

_exported_modules = ( "ITMSET_PRO", )

# The end.
