# Python stubs generated by omniidl from ITMSET.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


# #include "IBASE.idl"
import IBASE_idl
_0_IBASE = omniORB.openModule("IBASE")
_0_IBASE__POA = omniORB.openModule("IBASE__POA")

# #include "IMIB.idl"
import IMIB_idl
_0_IMIB = omniORB.openModule("IMIB")
_0_IMIB__POA = omniORB.openModule("IMIB__POA")

# #include "ITM.idl"
import ITM_idl
_0_ITM = omniORB.openModule("ITM")
_0_ITM__POA = omniORB.openModule("ITM__POA")

#
# Start of module "ITMSET"
#
__name__ = "ITMSET"
_0_ITMSET = omniORB.openModule("ITMSET", r"ITMSET.idl")
_0_ITMSET__POA = omniORB.openModule("ITMSET__POA", r"ITMSET.idl")

_0_ITMSET.PARAM_FILTERED_VALUE = 2048

# struct ParamRegisterCrit
_0_ITMSET.ParamRegisterCrit = omniORB.newEmptyClass()
class ParamRegisterCrit (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ITMSET/ParamRegisterCrit:1.0"

    def __init__(self, m_key, m_name, m_criterias, m_onlyWhenChange, m_onlyOnce):
        self.m_key = m_key
        self.m_name = m_name
        self.m_criterias = m_criterias
        self.m_onlyWhenChange = m_onlyWhenChange
        self.m_onlyOnce = m_onlyOnce

_0_ITMSET.ParamRegisterCrit = ParamRegisterCrit
_0_ITMSET._d_ParamRegisterCrit  = (omniORB.tcInternal.tv_struct, ParamRegisterCrit, ParamRegisterCrit._NP_RepositoryId, "ParamRegisterCrit", "m_key", omniORB.tcInternal.tv_long, "m_name", (omniORB.tcInternal.tv_string,0), "m_criterias", omniORB.typeMapping["IDL:IMIB/ParamValueType:1.0"], "m_onlyWhenChange", omniORB.typeMapping["IDL:IMIB/ParamValueType:1.0"], "m_onlyOnce", omniORB.tcInternal.tv_boolean)
_0_ITMSET._tc_ParamRegisterCrit = omniORB.tcInternal.createTypeCode(_0_ITMSET._d_ParamRegisterCrit)
omniORB.registerType(ParamRegisterCrit._NP_RepositoryId, _0_ITMSET._d_ParamRegisterCrit, _0_ITMSET._tc_ParamRegisterCrit)
del ParamRegisterCrit

# typedef ... ParamRegisterCrits
class ParamRegisterCrits:
    _NP_RepositoryId = "IDL:ITMSET/ParamRegisterCrits:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ITMSET.ParamRegisterCrits = ParamRegisterCrits
_0_ITMSET._d_ParamRegisterCrits  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMSET/ParamRegisterCrit:1.0"], 0)
_0_ITMSET._ad_ParamRegisterCrits = (omniORB.tcInternal.tv_alias, ParamRegisterCrits._NP_RepositoryId, "ParamRegisterCrits", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMSET/ParamRegisterCrit:1.0"], 0))
_0_ITMSET._tc_ParamRegisterCrits = omniORB.tcInternal.createTypeCode(_0_ITMSET._ad_ParamRegisterCrits)
omniORB.registerType(ParamRegisterCrits._NP_RepositoryId, _0_ITMSET._ad_ParamRegisterCrits, _0_ITMSET._tc_ParamRegisterCrits)
del ParamRegisterCrits

# struct SetRegisterCrit
_0_ITMSET.SetRegisterCrit = omniORB.newEmptyClass()
class SetRegisterCrit (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ITMSET/SetRegisterCrit:1.0"

    def __init__(self, m_key, m_paramEntries):
        self.m_key = m_key
        self.m_paramEntries = m_paramEntries

_0_ITMSET.SetRegisterCrit = SetRegisterCrit
_0_ITMSET._d_SetRegisterCrit  = (omniORB.tcInternal.tv_struct, SetRegisterCrit, SetRegisterCrit._NP_RepositoryId, "SetRegisterCrit", "m_key", omniORB.tcInternal.tv_long, "m_paramEntries", omniORB.typeMapping["IDL:ITMSET/ParamRegisterCrits:1.0"])
_0_ITMSET._tc_SetRegisterCrit = omniORB.tcInternal.createTypeCode(_0_ITMSET._d_SetRegisterCrit)
omniORB.registerType(SetRegisterCrit._NP_RepositoryId, _0_ITMSET._d_SetRegisterCrit, _0_ITMSET._tc_SetRegisterCrit)
del SetRegisterCrit

# union ParamAttribute
_0_ITMSET.ParamAttribute = omniORB.newEmptyClass()
class ParamAttribute (omniORB.Union):
    _NP_RepositoryId = "IDL:ITMSET/ParamAttribute:1.0"

_0_ITMSET.ParamAttribute = ParamAttribute

ParamAttribute._m_to_d = {"m_rawValue": 16, "m_engValue": 32, "m_synValue": 64, "m_sourceValue": 256, "m_defaultValue": 512, "m_filteredValue": 2048, "m_oolState": 4096, "m_sccState": 8192}
ParamAttribute._d_to_m = {16: "m_rawValue", 32: "m_engValue", 64: "m_synValue", 256: "m_sourceValue", 512: "m_defaultValue", 2048: "m_filteredValue", 4096: "m_oolState", 8192: "m_sccState"}
ParamAttribute._def_m  = None
ParamAttribute._def_d  = None

_0_ITMSET._m_ParamAttribute  = ((16, "m_rawValue", omniORB.typeMapping["IDL:ITM/ReducedValue:1.0"]), (32, "m_engValue", omniORB.typeMapping["IDL:ITM/ReducedValue:1.0"]), (64, "m_synValue", omniORB.typeMapping["IDL:ITM/ReducedValue:1.0"]), (256, "m_sourceValue", omniORB.typeMapping["IDL:ITM/ReducedValue:1.0"]), (512, "m_defaultValue", omniORB.typeMapping["IDL:ITM/ReducedValue:1.0"]), (2048, "m_filteredValue", omniORB.typeMapping["IDL:ITM/ReducedValue:1.0"]), (4096, "m_oolState", omniORB.typeMapping["IDL:ITM/OOLstate:1.0"]), (8192, "m_sccState", omniORB.typeMapping["IDL:ITM/SCCstate:1.0"]),)
_0_ITMSET._d_ParamAttribute  = (omniORB.tcInternal.tv_union, ParamAttribute, ParamAttribute._NP_RepositoryId, "ParamAttribute", omniORB.typeMapping["IDL:IMIB/ParamValueType:1.0"], -1, _0_ITMSET._m_ParamAttribute, None, {16: _0_ITMSET._m_ParamAttribute[0], 32: _0_ITMSET._m_ParamAttribute[1], 64: _0_ITMSET._m_ParamAttribute[2], 256: _0_ITMSET._m_ParamAttribute[3], 512: _0_ITMSET._m_ParamAttribute[4], 2048: _0_ITMSET._m_ParamAttribute[5], 4096: _0_ITMSET._m_ParamAttribute[6], 8192: _0_ITMSET._m_ParamAttribute[7]})
_0_ITMSET._tc_ParamAttribute = omniORB.tcInternal.createTypeCode(_0_ITMSET._d_ParamAttribute)
omniORB.registerType(ParamAttribute._NP_RepositoryId, _0_ITMSET._d_ParamAttribute, _0_ITMSET._tc_ParamAttribute)
del ParamAttribute

# typedef ... ParamAttributes
class ParamAttributes:
    _NP_RepositoryId = "IDL:ITMSET/ParamAttributes:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ITMSET.ParamAttributes = ParamAttributes
_0_ITMSET._d_ParamAttributes  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMSET/ParamAttribute:1.0"], 0)
_0_ITMSET._ad_ParamAttributes = (omniORB.tcInternal.tv_alias, ParamAttributes._NP_RepositoryId, "ParamAttributes", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMSET/ParamAttribute:1.0"], 0))
_0_ITMSET._tc_ParamAttributes = omniORB.tcInternal.createTypeCode(_0_ITMSET._ad_ParamAttributes)
omniORB.registerType(ParamAttributes._NP_RepositoryId, _0_ITMSET._ad_ParamAttributes, _0_ITMSET._tc_ParamAttributes)
del ParamAttributes

# struct ParamNotifyData
_0_ITMSET.ParamNotifyData = omniORB.newEmptyClass()
class ParamNotifyData (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ITMSET/ParamNotifyData:1.0"

    def __init__(self, m_key, m_sampleTime, m_attributes, m_tmPktDataIndexes):
        self.m_key = m_key
        self.m_sampleTime = m_sampleTime
        self.m_attributes = m_attributes
        self.m_tmPktDataIndexes = m_tmPktDataIndexes

_0_ITMSET.ParamNotifyData = ParamNotifyData
_0_ITMSET._d_ParamNotifyData  = (omniORB.tcInternal.tv_struct, ParamNotifyData, ParamNotifyData._NP_RepositoryId, "ParamNotifyData", "m_key", omniORB.tcInternal.tv_long, "m_sampleTime", omniORB.typeMapping["IDL:IBASE/Time:1.0"], "m_attributes", omniORB.typeMapping["IDL:ITMSET/ParamAttributes:1.0"], "m_tmPktDataIndexes", omniORB.typeMapping["IDL:IBASE/Longs:1.0"])
_0_ITMSET._tc_ParamNotifyData = omniORB.tcInternal.createTypeCode(_0_ITMSET._d_ParamNotifyData)
omniORB.registerType(ParamNotifyData._NP_RepositoryId, _0_ITMSET._d_ParamNotifyData, _0_ITMSET._tc_ParamNotifyData)
del ParamNotifyData

# typedef ... ParamNotifyDatas
class ParamNotifyDatas:
    _NP_RepositoryId = "IDL:ITMSET/ParamNotifyDatas:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ITMSET.ParamNotifyDatas = ParamNotifyDatas
_0_ITMSET._d_ParamNotifyDatas  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMSET/ParamNotifyData:1.0"], 0)
_0_ITMSET._ad_ParamNotifyDatas = (omniORB.tcInternal.tv_alias, ParamNotifyDatas._NP_RepositoryId, "ParamNotifyDatas", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMSET/ParamNotifyData:1.0"], 0))
_0_ITMSET._tc_ParamNotifyDatas = omniORB.tcInternal.createTypeCode(_0_ITMSET._ad_ParamNotifyDatas)
omniORB.registerType(ParamNotifyDatas._NP_RepositoryId, _0_ITMSET._ad_ParamNotifyDatas, _0_ITMSET._tc_ParamNotifyDatas)
del ParamNotifyDatas

# struct SetNotifyData
_0_ITMSET.SetNotifyData = omniORB.newEmptyClass()
class SetNotifyData (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ITMSET/SetNotifyData:1.0"

    def __init__(self, m_key, m_paramEntries):
        self.m_key = m_key
        self.m_paramEntries = m_paramEntries

_0_ITMSET.SetNotifyData = SetNotifyData
_0_ITMSET._d_SetNotifyData  = (omniORB.tcInternal.tv_struct, SetNotifyData, SetNotifyData._NP_RepositoryId, "SetNotifyData", "m_key", omniORB.tcInternal.tv_long, "m_paramEntries", omniORB.typeMapping["IDL:ITMSET/ParamNotifyDatas:1.0"])
_0_ITMSET._tc_SetNotifyData = omniORB.tcInternal.createTypeCode(_0_ITMSET._d_SetNotifyData)
omniORB.registerType(SetNotifyData._NP_RepositoryId, _0_ITMSET._d_SetNotifyData, _0_ITMSET._tc_SetNotifyData)
del SetNotifyData

# typedef ... SetNotifyDatas
class SetNotifyDatas:
    _NP_RepositoryId = "IDL:ITMSET/SetNotifyDatas:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ITMSET.SetNotifyDatas = SetNotifyDatas
_0_ITMSET._d_SetNotifyDatas  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMSET/SetNotifyData:1.0"], 0)
_0_ITMSET._ad_SetNotifyDatas = (omniORB.tcInternal.tv_alias, SetNotifyDatas._NP_RepositoryId, "SetNotifyDatas", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMSET/SetNotifyData:1.0"], 0))
_0_ITMSET._tc_SetNotifyDatas = omniORB.tcInternal.createTypeCode(_0_ITMSET._ad_SetNotifyDatas)
omniORB.registerType(SetNotifyDatas._NP_RepositoryId, _0_ITMSET._ad_SetNotifyDatas, _0_ITMSET._tc_SetNotifyDatas)
del SetNotifyDatas

# struct TransmissionFilter
_0_ITMSET.TransmissionFilter = omniORB.newEmptyClass()
class TransmissionFilter (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ITMSET/TransmissionFilter:1.0"

    def __init__(self, m_transmitData, m_transmitPacketHeader, m_transmitPacketHeaderRawData, m_transmitPacketBodyRawData):
        self.m_transmitData = m_transmitData
        self.m_transmitPacketHeader = m_transmitPacketHeader
        self.m_transmitPacketHeaderRawData = m_transmitPacketHeaderRawData
        self.m_transmitPacketBodyRawData = m_transmitPacketBodyRawData

_0_ITMSET.TransmissionFilter = TransmissionFilter
_0_ITMSET._d_TransmissionFilter  = (omniORB.tcInternal.tv_struct, TransmissionFilter, TransmissionFilter._NP_RepositoryId, "TransmissionFilter", "m_transmitData", omniORB.tcInternal.tv_boolean, "m_transmitPacketHeader", omniORB.tcInternal.tv_boolean, "m_transmitPacketHeaderRawData", omniORB.tcInternal.tv_boolean, "m_transmitPacketBodyRawData", omniORB.tcInternal.tv_boolean)
_0_ITMSET._tc_TransmissionFilter = omniORB.tcInternal.createTypeCode(_0_ITMSET._d_TransmissionFilter)
omniORB.registerType(TransmissionFilter._NP_RepositoryId, _0_ITMSET._d_TransmissionFilter, _0_ITMSET._tc_TransmissionFilter)
del TransmissionFilter

# struct PacketHeader
_0_ITMSET.PacketHeader = omniORB.newEmptyClass()
class PacketHeader (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ITMSET/PacketHeader:1.0"

    def __init__(self, m_commonHeader, m_pktValidity, m_Tpsd, m_RouteId, m_PusApid, m_PusSrcSeqCnt, m_PusSrvcType, m_PusSrvcSubType, m_pktId):
        self.m_commonHeader = m_commonHeader
        self.m_pktValidity = m_pktValidity
        self.m_Tpsd = m_Tpsd
        self.m_RouteId = m_RouteId
        self.m_PusApid = m_PusApid
        self.m_PusSrcSeqCnt = m_PusSrcSeqCnt
        self.m_PusSrvcType = m_PusSrvcType
        self.m_PusSrvcSubType = m_PusSrvcSubType
        self.m_pktId = m_pktId

_0_ITMSET.PacketHeader = PacketHeader
_0_ITMSET._d_PacketHeader  = (omniORB.tcInternal.tv_struct, PacketHeader, PacketHeader._NP_RepositoryId, "PacketHeader", "m_commonHeader", omniORB.typeMapping["IDL:IBASE/CommonPktHeader:1.0"], "m_pktValidity", omniORB.tcInternal.tv_ulong, "m_Tpsd", omniORB.tcInternal.tv_long, "m_RouteId", omniORB.tcInternal.tv_ushort, "m_PusApid", omniORB.tcInternal.tv_ushort, "m_PusSrcSeqCnt", omniORB.tcInternal.tv_ushort, "m_PusSrvcType", omniORB.tcInternal.tv_octet, "m_PusSrvcSubType", omniORB.tcInternal.tv_octet, "m_pktId", (omniORB.tcInternal.tv_string,0))
_0_ITMSET._tc_PacketHeader = omniORB.tcInternal.createTypeCode(_0_ITMSET._d_PacketHeader)
omniORB.registerType(PacketHeader._NP_RepositoryId, _0_ITMSET._d_PacketHeader, _0_ITMSET._tc_PacketHeader)
del PacketHeader

# typedef ... PacketHeaders
class PacketHeaders:
    _NP_RepositoryId = "IDL:ITMSET/PacketHeaders:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ITMSET.PacketHeaders = PacketHeaders
_0_ITMSET._d_PacketHeaders  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMSET/PacketHeader:1.0"], 0)
_0_ITMSET._ad_PacketHeaders = (omniORB.tcInternal.tv_alias, PacketHeaders._NP_RepositoryId, "PacketHeaders", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMSET/PacketHeader:1.0"], 0))
_0_ITMSET._tc_PacketHeaders = omniORB.tcInternal.createTypeCode(_0_ITMSET._ad_PacketHeaders)
omniORB.registerType(PacketHeaders._NP_RepositoryId, _0_ITMSET._ad_PacketHeaders, _0_ITMSET._tc_PacketHeaders)
del PacketHeaders

# struct PacketData
_0_ITMSET.PacketData = omniORB.newEmptyClass()
class PacketData (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ITMSET/PacketData:1.0"

    def __init__(self, m_pktHeader, m_pktHeaderRawData, m_pktBodyRawData):
        self.m_pktHeader = m_pktHeader
        self.m_pktHeaderRawData = m_pktHeaderRawData
        self.m_pktBodyRawData = m_pktBodyRawData

_0_ITMSET.PacketData = PacketData
_0_ITMSET._d_PacketData  = (omniORB.tcInternal.tv_struct, PacketData, PacketData._NP_RepositoryId, "PacketData", "m_pktHeader", omniORB.typeMapping["IDL:ITMSET/PacketHeaders:1.0"], "m_pktHeaderRawData", omniORB.typeMapping["IDL:IBASE/ByteString:1.0"], "m_pktBodyRawData", omniORB.typeMapping["IDL:IBASE/ByteString:1.0"])
_0_ITMSET._tc_PacketData = omniORB.tcInternal.createTypeCode(_0_ITMSET._d_PacketData)
omniORB.registerType(PacketData._NP_RepositoryId, _0_ITMSET._d_PacketData, _0_ITMSET._tc_PacketData)
del PacketData

# typedef ... PacketDatas
class PacketDatas:
    _NP_RepositoryId = "IDL:ITMSET/PacketDatas:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ITMSET.PacketDatas = PacketDatas
_0_ITMSET._d_PacketDatas  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMSET/PacketData:1.0"], 0)
_0_ITMSET._ad_PacketDatas = (omniORB.tcInternal.tv_alias, PacketDatas._NP_RepositoryId, "PacketDatas", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ITMSET/PacketData:1.0"], 0))
_0_ITMSET._tc_PacketDatas = omniORB.tcInternal.createTypeCode(_0_ITMSET._ad_PacketDatas)
omniORB.registerType(PacketDatas._NP_RepositoryId, _0_ITMSET._ad_PacketDatas, _0_ITMSET._tc_PacketDatas)
del PacketDatas

# struct ClientNotifyData
_0_ITMSET.ClientNotifyData = omniORB.newEmptyClass()
class ClientNotifyData (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ITMSET/ClientNotifyData:1.0"

    def __init__(self, m_tmPktTime, m_setEntries, m_tmPktData):
        self.m_tmPktTime = m_tmPktTime
        self.m_setEntries = m_setEntries
        self.m_tmPktData = m_tmPktData

_0_ITMSET.ClientNotifyData = ClientNotifyData
_0_ITMSET._d_ClientNotifyData  = (omniORB.tcInternal.tv_struct, ClientNotifyData, ClientNotifyData._NP_RepositoryId, "ClientNotifyData", "m_tmPktTime", omniORB.typeMapping["IDL:IBASE/Time:1.0"], "m_setEntries", omniORB.typeMapping["IDL:ITMSET/SetNotifyDatas:1.0"], "m_tmPktData", omniORB.typeMapping["IDL:ITMSET/PacketDatas:1.0"])
_0_ITMSET._tc_ClientNotifyData = omniORB.tcInternal.createTypeCode(_0_ITMSET._d_ClientNotifyData)
omniORB.registerType(ClientNotifyData._NP_RepositoryId, _0_ITMSET._d_ClientNotifyData, _0_ITMSET._tc_ClientNotifyData)
del ClientNotifyData

#
# End of module "ITMSET"
#
__name__ = "ITMSET_idl"

_exported_modules = ( "ITMSET", )

# The end.
