# Python stubs generated by omniidl from IUSER_IF.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


# #include "IBASE.idl"
import IBASE_idl
_0_IBASE = omniORB.openModule("IBASE")
_0_IBASE__POA = omniORB.openModule("IBASE__POA")

#
# Start of module "IUSER_IF"
#
__name__ = "IUSER_IF"
_0_IUSER_IF = omniORB.openModule("IUSER_IF", r"IUSER_IF.idl")
_0_IUSER_IF__POA = omniORB.openModule("IUSER_IF__POA", r"IUSER_IF.idl")


# interface UserMngr
_0_IUSER_IF._d_UserMngr = (omniORB.tcInternal.tv_objref, "IDL:IUSER_IF/UserMngr:1.0", "UserMngr")
omniORB.typeMapping["IDL:IUSER_IF/UserMngr:1.0"] = _0_IUSER_IF._d_UserMngr
_0_IUSER_IF.UserMngr = omniORB.newEmptyClass()
class UserMngr :
    _NP_RepositoryId = _0_IUSER_IF._d_UserMngr[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil

    ServiceName = "USER_001"


_0_IUSER_IF.UserMngr = UserMngr
_0_IUSER_IF._tc_UserMngr = omniORB.tcInternal.createTypeCode(_0_IUSER_IF._d_UserMngr)
omniORB.registerType(UserMngr._NP_RepositoryId, _0_IUSER_IF._d_UserMngr, _0_IUSER_IF._tc_UserMngr)

# UserMngr operations and attributes
UserMngr._d_setUserData = (((omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:IBASE/ByteString:1.0"]), (), {_0_IBASE.NotFound._NP_RepositoryId: _0_IBASE._d_NotFound})
UserMngr._d_getUserData = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:IBASE/ByteString:1.0"], ), {_0_IBASE.NotFound._NP_RepositoryId: _0_IBASE._d_NotFound})

# UserMngr object reference
class _objref_UserMngr (CORBA.Object):
    _NP_RepositoryId = UserMngr._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def setUserData(self, *args):
        return self._obj.invoke("setUserData", _0_IUSER_IF.UserMngr._d_setUserData, args)

    def getUserData(self, *args):
        return self._obj.invoke("getUserData", _0_IUSER_IF.UserMngr._d_getUserData, args)

omniORB.registerObjref(UserMngr._NP_RepositoryId, _objref_UserMngr)
_0_IUSER_IF._objref_UserMngr = _objref_UserMngr
del UserMngr, _objref_UserMngr

# UserMngr skeleton
__name__ = "IUSER_IF__POA"
class UserMngr (PortableServer.Servant):
    _NP_RepositoryId = _0_IUSER_IF.UserMngr._NP_RepositoryId


    _omni_op_d = {"setUserData": _0_IUSER_IF.UserMngr._d_setUserData, "getUserData": _0_IUSER_IF.UserMngr._d_getUserData}

UserMngr._omni_skeleton = UserMngr
_0_IUSER_IF__POA.UserMngr = UserMngr
omniORB.registerSkeleton(UserMngr._NP_RepositoryId, UserMngr)
del UserMngr
__name__ = "IUSER_IF"

#
# End of module "IUSER_IF"
#
__name__ = "IUSER_IF_idl"

_exported_modules = ( "IUSER_IF", )

# The end.
