# DO NOT EDIT THIS FILE!
#
# Python module IEV__POA generated by omniidl

import omniORB
omniORB.updateModule("IEV__POA")

# ** 1. Stub files contributing to this module
import IEV_idl

# ** 2. Sub-modules

# ** 3. End
