# DO NOT EDIT THIS FILE!
#
# Python module ITC_INJ_INTL generated by omniidl

import omniORB
omniORB.updateModule("ITC_INJ_INTL")

# ** 1. Stub files contributing to this module
import ITC_INJ_INTL_idl

# ** 2. Sub-modules

# ** 3. End
