# DO NOT EDIT THIS FILE!
#
# Python module ITM_INJ generated by omniidl

import omniORB
omniORB.updateModule("ITM_INJ")

# ** 1. Stub files contributing to this module
import ITM_INJ_idl

# ** 2. Sub-modules

# ** 3. End
