# DO NOT EDIT THIS FILE!
#
# Python module ICLOCK_PRO generated by omniidl

import omniORB
omniORB.updateModule("ICLOCK_PRO")

# ** 1. Stub files contributing to this module
import ICLOCK_PRO_idl

# ** 2. Sub-modules

# ** 3. End
