# DO NOT EDIT THIS FILE!
#
# Python module ITM_PRO generated by omniidl

import omniORB
omniORB.updateModule("ITM_PRO")

# ** 1. Stub files contributing to this module
import ITM_PRO_idl

# ** 2. Sub-modules

# ** 3. End
