# DO NOT EDIT THIS FILE!
#
# Python module ITMP generated by omniidl

import omniORB
omniORB.updateModule("ITMP")

# ** 1. Stub files contributing to this module
import ITMP_idl

# ** 2. Sub-modules

# ** 3. End
