# DO NOT EDIT THIS FILE!
#
# Python module ITMSET_PRO__POA generated by omniidl

import omniORB
omniORB.updateModule("ITMSET_PRO__POA")

# ** 1. Stub files contributing to this module
import ITMSET_PRO_idl

# ** 2. Sub-modules

# ** 3. End
