# DO NOT EDIT THIS FILE!
#
# Python module IMIB__POA generated by omniidl

import omniORB
omniORB.updateModule("IMIB__POA")

# ** 1. Stub files contributing to this module
import IMIB_idl

# ** 2. Sub-modules

# ** 3. End
