# DO NOT EDIT THIS FILE!
#
# Python module IUSER_IF generated by omniidl

import omniORB
omniORB.updateModule("IUSER_IF")

# ** 1. Stub files contributing to this module
import IUSER_IF_idl

# ** 2. Sub-modules

# ** 3. End
