# DO NOT EDIT THIS FILE!
#
# Python module ITC__POA generated by omniidl

import omniORB
omniORB.updateModule("ITC__POA")

# ** 1. Stub files contributing to this module
import ITC_idl

# ** 2. Sub-modules

# ** 3. End
