# DO NOT EDIT THIS FILE!
#
# Python module ITC_PRO generated by omniidl

import omniORB
omniORB.updateModule("ITC_PRO")

# ** 1. Stub files contributing to this module
import ITC_PRO_idl

# ** 2. Sub-modules

# ** 3. End
