# DO NOT EDIT THIS FILE!
#
# Python module ITM__POA generated by omniidl

import omniORB
omniORB.updateModule("ITM__POA")

# ** 1. Stub files contributing to this module
import ITM_idl

# ** 2. Sub-modules

# ** 3. End
