# DO NOT EDIT THIS FILE!
#
# Python module ITMP_PRO generated by omniidl

import omniORB
omniORB.updateModule("ITMP_PRO")

# ** 1. Stub files contributing to this module
import ITMP_PRO_idl

# ** 2. Sub-modules

# ** 3. End
