# DO NOT EDIT THIS FILE!
#
# Python module IBASE__POA generated by omniidl

import omniORB
omniORB.updateModule("IBASE__POA")

# ** 1. Stub files contributing to this module
import IBASE_idl

# ** 2. Sub-modules

# ** 3. End
