# DO NOT EDIT THIS FILE!
#
# Python module ITC_INJ generated by omniidl

import omniORB
omniORB.updateModule("ITC_INJ")

# ** 1. Stub files contributing to this module
import ITC_INJ_idl

# ** 2. Sub-modules

# ** 3. End
