# DO NOT EDIT THIS FILE!
#
# Python module IBASE_IF__POA generated by omniidl

import omniORB
omniORB.updateModule("IBASE_IF__POA")

# ** 1. Stub files contributing to this module
import IBASE_IF_idl

# ** 2. Sub-modules

# ** 3. End
