# DO NOT EDIT THIS FILE!
#
# Python module ICLOCK generated by omniidl

import omniORB
omniORB.updateModule("ICLOCK")

# ** 1. Stub files contributing to this module
import ICLOCK_idl

# ** 2. Sub-modules

# ** 3. End
